import base64
import json
import os
import subprocess
import typing

NOTE = (
    "> ##### This pr was automatically generated by "
    "[agents-nix-bot](https://github.com/apps/agents-nix-bot)."
)


def run(*args: str, stdin: str | None = None, check: bool = True) -> str:
    return subprocess.run(
        args,
        input=stdin,
        stdout=subprocess.PIPE,
        stderr=None if check else subprocess.DEVNULL,
        text=True,
        check=check,
    ).stdout


def git(*args: str, check: bool = True) -> str:
    return run("git", *args, check=check)


def blob_at(rev: str, path: str) -> str | None:
    found = git(
        "rev-parse", "--verify", "--quiet", f"{rev}:{path}", check=False
    )
    return found.strip() or None


def api(
    path: str, body: dict[str, typing.Any] | None = None, method: str = "GET"
) -> typing.Any:
    url = f"repos/{os.environ['GITHUB_REPOSITORY']}/{path}"
    args = ["gh", "api", "-X", method, url]
    if body is not None:
        args += ["--input", "-"]
    out = run(*args, stdin=json.dumps(body) if body is not None else None)
    return json.loads(out) if out.strip() else None


def put_file(
    path: str, branch: str, message: str, content: bytes, sha: str | None
) -> None:
    """Commit a file through the API, which signs it."""
    body = {
        "message": message,
        "branch": branch,
        "content": base64.b64encode(content).decode(),
    }
    api(f"contents/{path}", body | ({"sha": sha} if sha else {}), "PUT")


def delete_file(path: str, branch: str, message: str, base: str) -> None:
    # a delete through the contents api lands unsigned, so it goes the long way
    tree = api(
        "git/trees",
        {
            "base_tree": git("rev-parse", f"{base}^{{tree}}").strip(),
            "tree": [
                {"path": path, "mode": "100644", "type": "blob", "sha": None}
            ],
        },
        "POST",
    )["sha"]
    commit = api(
        "git/commits",
        {"message": message, "tree": tree, "parents": [base]},
        "POST",
    )["sha"]
    api(f"git/refs/heads/{branch}", {"sha": commit, "force": True}, "PATCH")


def open_pr(branch: str) -> int | None:
    found = run(
        "gh", "pr", "list", "--head", branch, "--state", "open",
        "--json", "number", "--jq", ".[0].number // empty",
    ).strip()  # fmt: skip
    return int(found) if found else None


def propose(branch: str, title: str, body: str, retitle: bool = False) -> None:
    number = open_pr(branch)
    if number is None:
        run(
            "gh", "pr", "create", "--head", branch, "--base", "main",
            "--title", title, "--body", body,
        )  # fmt: skip
    elif retitle:
        run("gh", "pr", "edit", str(number), "--title", title, "--body", body)
    merge = ["gh", "pr", "merge", "--auto", "--squash", branch]
    if subprocess.run(merge, check=False).returncode == 0:
        return
    # it may have merged already, or be waiting to
    waiting = run(
        "gh", "pr", "view", branch, "--json", "state,autoMergeRequest",
        "--jq", '.state == "MERGED" or (.state == "OPEN" and '
        ".autoMergeRequest != null)",
    ).strip()  # fmt: skip
    if waiting != "true":
        raise OSError(f"could not set {branch} to merge")
