import base64
import collections.abc
import email.parser
import hashlib
import json
import os
import subprocess
import sys
import time
import typing
from urllib.parse import quote, urlencode

import urllib3

NOTE = (
    "> ##### This pr was automatically generated by "
    "[agents-nix-bot](https://github.com/apps/agents-nix-bot)."
)


def run(*args: str, stdin: str | None = None, check: bool = True) -> str:
    return subprocess.run(
        args,
        input=stdin,
        stdout=subprocess.PIPE,
        stderr=None if check else subprocess.DEVNULL,
        text=True,
        check=check,
    ).stdout


def git(*args: str, check: bool = True) -> str:
    return run("git", *args, check=check)


def blob_at(rev: str, path: str) -> str | None:
    found = git(
        "rev-parse", "--verify", "--quiet", f"{rev}:{path}", check=False
    )
    return found.strip() or None


class ApiError(subprocess.CalledProcessError):
    def __init__(
        self,
        result: subprocess.CompletedProcess[str],
        status: int,
        headers: dict[str, str],
    ) -> None:
        super().__init__(
            result.returncode or 1, result.args, result.stdout, result.stderr
        )
        self.status = status
        self.headers = headers
        self.exhausted = False

    def __str__(self) -> str:
        return f"{super().__str__()}: {self.stderr.strip()}"

    def delay(self, attempt: int) -> float | None:
        if self.status == 200 and "rate limit" not in self.stderr.lower():
            return None
        if self.status in {200, 403, 429}:
            if value := self.headers.get("retry-after"):
                return urllib3.Retry().parse_retry_after(value)
            if self.headers.get("x-ratelimit-remaining") == "0":
                return max(
                    0,
                    float(self.headers["x-ratelimit-reset"]) - time.time() + 1,
                )
            if self.status == 429 or "rate limit" in self.stderr.lower():
                return 60 * 2**attempt
            return None
        if self.status in {500, 502, 503, 504}:
            return 2 ** (attempt + 1)
        if self.status == 0 and any(
            word in self.stderr.lower()
            for word in (
                "timeout",
                "timed out",
                "connection reset",
                "connection refused",
                "unexpected eof",
                ": eof",
                "broken pipe",
                "network is unreachable",
                "connection closed",
                "no such host",
                "temporary failure",
            )
        ):
            return 2 ** (attempt + 1)
        return None


def retry[T](
    action: collections.abc.Callable[[], T],
    confirmed: collections.abc.Callable[[], bool] | None = None,
) -> T | None:
    for attempt in range(3):
        if attempt and confirmed is not None and confirmed():
            return None
        try:
            return action()
        except ApiError as error:
            if error.exhausted:
                raise
            delay = error.delay(attempt)
            if delay is None or attempt == 2:
                if (
                    confirmed is not None
                    and error.status not in {401, 403, 429}
                    and not (error.status == 200 and delay is not None)
                    and confirmed()
                ):
                    return None
                error.exhausted = True
                raise
            print(
                f"::notice::GitHub request failed; retrying in {delay:.0f}s",
                file=sys.stderr,
            )
            time.sleep(delay)
    raise AssertionError("unreachable")


def api(
    path: str, body: dict[str, typing.Any] | None = None, method: str = "GET"
) -> typing.Any:
    url = (
        path.removeprefix("/")
        if path.startswith("/")
        else f"repos/{os.environ['GITHUB_REPOSITORY']}/{path}"
    )
    args = ["gh", "api", "--include", "-X", method, url]
    if body is not None:
        args += ["--input", "-"]

    def request() -> typing.Any:
        result = subprocess.run(
            args,
            input=json.dumps(body) if body is not None else None,
            capture_output=True,
            text=True,
            check=False,
        )
        head, separator, payload = result.stdout.partition("\n\n")
        status = int(head.split()[1]) if separator else 0
        parsed = email.parser.Parser().parsestr(head.partition("\n")[2])
        headers = {key.lower(): value for key, value in parsed.items()}
        if result.returncode:
            raise ApiError(result, status, headers)
        return json.loads(payload) if payload.strip() else None

    return retry(request) if method == "GET" else request()


def prepare_branch(branch: str, base: str) -> None:
    path = f"git/ref/heads/{quote(branch, safe='/')}"

    def current() -> str | None:
        try:
            return api(path)["object"]["sha"]
        except ApiError as error:
            if error.status != 404:
                raise
            return None

    old = current()
    if old == base:
        return

    def confirmed() -> bool:
        now = current()
        if now == base:
            return True
        if now != old:
            raise OSError(f"{branch} changed while preparing it")
        return False

    endpoint = path.replace("git/ref/", "git/refs/", 1) if old else "git/refs"
    body = (
        {"sha": base, "force": True}
        if old
        else {
            "ref": f"refs/heads/{branch}",
            "sha": base,
        }
    )
    retry(lambda: api(endpoint, body, "PATCH" if old else "POST"), confirmed)


def put_file(
    path: str, branch: str, message: str, content: bytes, sha: str | None
) -> None:
    """Commit a file through the API, which signs it."""
    body = {
        "message": message,
        "branch": branch,
        "content": base64.b64encode(content).decode(),
    }
    wanted = hashlib.sha1(
        f"blob {len(content)}\0".encode() + content, usedforsecurity=False
    ).hexdigest()
    endpoint = f"contents/{quote(path, safe='/')}"

    def confirmed() -> bool:
        try:
            now = api(f"{endpoint}?{urlencode({'ref': branch})}")["sha"]
        except ApiError as error:
            if error.status != 404:
                raise
            now = None
        if now == wanted:
            return True
        if now != sha:
            raise OSError(f"{path} changed while committing it")
        return False

    retry(
        lambda: api(endpoint, body | ({"sha": sha} if sha else {}), "PUT"),
        confirmed,
    )


def open_pr(branch: str) -> int | None:
    owner = os.environ["GITHUB_REPOSITORY"].split("/", 1)[0]
    found = api(
        "pulls?"
        + urlencode({
            "head": f"{owner}:{branch}",
            "state": "open",
            "per_page": 1,
        })
    )
    return found[0]["number"] if found else None


def propose(branch: str, title: str, body: str, retitle: bool = False) -> None:
    number = open_pr(branch)
    if number is None:
        retry(
            lambda: api(
                "pulls",
                {"head": branch, "base": "main", "title": title, "body": body},
                "POST",
            ),
            lambda: open_pr(branch) is not None,
        )
        number = open_pr(branch)
    assert number is not None
    if retitle:
        retry(
            lambda: api(
                f"pulls/{number}", {"title": title, "body": body}, "PATCH"
            )
        )
    node = api(f"pulls/{number}")["node_id"]

    def state() -> typing.Any:
        payload = retry(
            lambda: api(
                "/graphql",
                {
                    "query": """query($id: ID!) {
              node(id: $id) { ... on PullRequest {
                state autoMergeRequest { enabledAt } mergeStateStatus headRefOid
                isInMergeQueue isMergeQueueEnabled
              } }
            }""",
                    "variables": {"id": node},
                },
                "POST",
            )
        )
        assert payload is not None
        return payload["data"]["node"]

    def confirmed() -> bool:
        now = state()
        return now["state"] == "MERGED" or (
            now["state"] == "OPEN"
            and (now["autoMergeRequest"] is not None or now["isInMergeQueue"])
        )

    def merge() -> None:
        now = state()
        if now["state"] == "MERGED" or (
            now["state"] == "OPEN"
            and (now["autoMergeRequest"] is not None or now["isInMergeQueue"])
        ):
            return
        if now["state"] != "OPEN":
            raise OSError(f"{branch} is closed without merging")
        immediate = (
            now["mergeStateStatus"]
            in {
                "CLEAN",
                "HAS_HOOKS",
                "UNSTABLE",
            }
            and not now["isMergeQueueEnabled"]
        )
        operation = (
            "mergePullRequest" if immediate else "enablePullRequestAutoMerge"
        )
        input_type = operation[0].upper() + operation[1:] + "Input"
        input = {"pullRequestId": node, "mergeMethod": "SQUASH"}
        if immediate:
            input["expectedHeadOid"] = now["headRefOid"]
        api(
            "/graphql",
            {
                "query": f"""mutation($input: {input_type}!) {{
              {operation}(input: $input) {{ pullRequest {{ id }} }}
            }}""",
                "variables": {"input": input},
            },
            "POST",
        )

    retry(merge, confirmed)
