name: Agent Plugins Fetch

on:
  schedule:
    - cron: "7 */6 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions: {}

jobs:
  sources:
    name: Sources
    uses: ./.github/workflows/sources.yml
    with:
      kind: agent-plugins
      sites: '["github-code", "github-topics"]'
    secrets: inherit
