name: Agent Plugins Update

on:
  schedule:
    - cron: "37 */3 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions: {}

jobs:
  update:
    name: Update
    uses: ./.github/workflows/update.yml
    with:
      kind: agent-plugins
      shards: "[1, 2]"
    secrets: inherit
