name: Copilot Marketplaces Fetch

on:
  schedule:
    - cron: "8 */6 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions: {}

jobs:
  sources:
    name: Sources
    uses: ./.github/workflows/sources.yml
    with:
      kind: copilot-marketplaces
      sites: '["github-code", "github-topics"]'
    secrets: inherit
