name: Copilot Marketplaces Update

on:
  schedule:
    - cron: "38 */3 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions: {}

jobs:
  update:
    name: Update
    uses: ./.github/workflows/update.yml
    with:
      kind: copilot-marketplaces
      shards: "[1, 2]"
    secrets: inherit
