name: Kiro Powers Update

on:
  schedule:
    - cron: "22 */3 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions: {}

jobs:
  update:
    name: Update
    uses: ./.github/workflows/update.yml
    with:
      kind: kiro-powers
      shards: "[1, 2]"
    secrets: inherit
